# -*- coding: utf-8 -*-
"""project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11akuG7AVHzLVczMxBCKZslwTeQp-CCGk
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_excel("/content/data_3.xlsx")
print(data.head())

numeric_data = data.select_dtypes(include="number")

corr = numeric_data.corr(method="pearson")
print(corr)

mask = np.triu(np.ones_like(corr, dtype=bool))

plt.figure(figsize=(8,6))
plt.imshow(corr, interpolation="nearest")
plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.columns)), corr.columns)

# Annotate values
for i in range(len(corr.columns)):
    for j in range(len(corr.columns)):
        if not mask[i, j]:
            plt.text(j, i, f"{corr.iloc[i, j]:.2f}",
                     ha="center", va="center")

plt.title("Correlation Heatmap (Pearson)")
plt.tight_layout()
plt.savefig("correlation_heatmap.png")
plt.close()

pd.plotting.scatter_matrix(
    numeric_data,
    figsize=(10,10),
    diagonal="hist"
)

plt.suptitle("Pairwise Relationships (Scatter Matrix)")
plt.tight_layout()
plt.savefig("pairwise_scatter_matrix.png")
plt.close()

corr_pairs = corr.unstack()
corr_pairs = corr_pairs[corr_pairs.index.get_level_values(0) != corr_pairs.index.get_level_values(1)]

strongest_positive = corr_pairs.sort_values(ascending=False).head(3)
strongest_negative = corr_pairs.sort_values().head(3)

print("Strongest Positive Correlations:")
print(strongest_positive)

print("\nStrongest Negative Correlations:")
print(strongest_negative)

interpretation = """
The correlation analysis shows a strong positive relationship between Sales and Profit,
indicating that higher sales lead to higher profitability. Marketing Spend is also
positively correlated with Sales and Quantity, suggesting effective marketing impact.
Discount shows a negative correlation with Profit, implying margin reduction at higher
discount levels. Scatter matrix plots confirm linear relationships between key variables
and highlight areas of strong association and minimal correlation.
"""

print(interpretation)